name: 'vscode-webdriverio Cache vscode'
description: 'cache the vscode for CI (Use after `pnpm install`)'
inputs:
    path:
        description: 'location to cache'
runs:
    using: 'composite'
    steps:
        - name: ğŸª„ Generate cache key
          id: generate-key
          run: pnpm --filter @vscode-wdio/release run cache-key
          shell: bash

        - name: ğŸ—ƒï¸ Use cached vscode
          if: ${{ steps.generate-key.outputs.vscode-cache-key != '' }}
          uses: actions/cache@v4.2.3
          with:
              path: ${{ inputs.path }}
              key: ${{ steps.generate-key.outputs.vscode-cache-key }}
