name: Auto Close Issue

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  close-not-reproducible-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.WDIO_BOT_GITHUB_TOKEN }}
          only-issue-labels: 'Reproducible Example Missing'
          stale-issue-label: ':classical_building: Stale'
          days-before-close: 0
          days-before-stale: 7
          close-issue-message: >
            Thanks for raising this issue ğŸ™

            Unfortunately, we are closing the issue as no reproducible samples were provided within 7 days.
            If there are any updates, please reopen this issue or create new one.

            If you have any questions please reach out to us on our [Discord](https://discord.webdriver.io/)
            channel. We are happy to help you out there.
